# Generated by Django 3.0.8 on 2020-07-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
