# Generated by Django 3.0.8 on 2020-07-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_pizza_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQueue',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.Order')),
                ('ordered_time', models.DateTimeField()),
            ],
        ),
    ]
