# Generated by Django 3.0.8 on 2020-07-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderqueue',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.Order', unique=True),
        ),
    ]
